# Generated by Django 6.0.4 on 2026-04-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='stock_in',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='priority',
            field=models.CharField(choices=[('Standard Production Batch', 'Standard Production Batch'), ('Defect Replacement', 'Defect Replacement'), ('R&D Prototype', 'R&D Prototype'), ('Maintenance Consumable', 'Maintenance Consumable')], default='Standard Production Batch', max_length=50),
        ),
    ]
