# Generated by Django 6.0.4 on 2026-04-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_category_inventoryitem_stock_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('Part', 'Part'), ('Fastener', 'Fastener')], default='Part', max_length=20),
        ),
    ]
