# Generated by Django 6.0.4 on 2026-05-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='daily_quota_hint',
            field=models.CharField(blank=True, help_text="e.g., 'Need 120 rims today'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='station',
            field=models.CharField(choices=[('Frame Assembly', 'Frame Assembly Station'), ('Handle Bar', 'Handle Bar Station'), ('Front Fork', 'Front Fork Station'), ('Bike Stand', 'Bike Stand Station'), ('Wheel Assembly', 'Wheel Assembly Station'), ('QC', 'QC Station'), ('General', 'General / Multiple Stations')], default='General', max_length=50),
        ),
    ]
