# Generated by Django 6.0.4 on 2026-05-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_daily_quota_hint_inventoryitem_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Front Wheel Assembly', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField(default=1, help_text='How many of this item are needed for this kit?')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.buildkit')),
            ],
        ),
    ]
